### ISSUE TITLE
use winscp into docker container using your stack

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/platys-modern-data-platform#593]
How can use WINSCP for edit yaml into each container using your stack?

pls view example in this video:

https://drive.google.com/file/d/1waD8EaUZyaMwZAXsUm-SgNHuRkYZsInh/view?usp=drivesdk

**Comment by gschmutz** [comment]
@johnfelipe this is not possible, as first you would need to know the IP address of each container and even if you do, these are not reachable from your windows computer. But if you copy into data-transfer folder, it will be mapped into the container as /data-transfer folder. If you want to edit a file in a container, you have to map if using an additional volume mapping. You can add the volume mapping using the `docker-compose.override.yml`, so that you don't have to change the `docker-compose.yml` so it will not cause any problem if you generate it again later.
